Add code with security and performance issues
deepsourcelabs/demo-go pull request #8
Opened 2020-11-10 22:02 UTC by siddhant-deepsource

2020-11-16 17:13 UTC, sourya-deepsource requested changes

2020-11-16 17:13 UTC, sourya-deepsource commented on sync_example.go
> +func Benchmark_LargeSize_Pool_ReturnNonpointer(b *testing.B) {
This should be just camel case, not a mix.

2020-11-16 17:13 UTC, sourya-deepsource commented on go.mod
> +go 1.13
```suggestion
go 1.13

require golang.org/x/crypto v0.0.0-20201116153603-4be66e5b6582
```

2020-11-16 17:19 UTC, siddhant-deepsource commented on sync_example.go
> +func Benchmark_LargeSize_Pool_ReturnNonpointer(b *testing.B) {
Done.

2020-11-16 17:21 UTC, sourya-deepsource commented on sync_example.go
> +const size = 64 * 1024 //65536
```suggestion
const size = 64 * 1024 // 65536
```

2020-11-19 09:52 UTC, sourya-deepsource approved these changes

2020-11-19 09:53 UTC, merged